<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace GPBMetadata;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7b0a0e6d657373616765732e70726f746f120967656e65726174656422" .
            "220a03466f6f121b0a0362617218012001280b320e2e67656e6572617465" .
            "642e42617222320a03426172122b0a056669656c6418012001280b321c2e" .
            "676f6f676c652e70726f746f6275662e537472696e6756616c7565620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

